server:
  servlet:
    context-path: /sell

spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.103:3306/sell?characterEncoding=utf8&useSSL=false

  # 打印sql
  jpa:
    show-sql: true
  # 序列化对象时 ， 忽略为null的属性
  jackson:
    default-property-inclusion: non_null

logging:
  file:
    path: ./